name: Hello world
run-name: Hello world ${{ inputs.name }} execution

on:
  workflow_dispatch:
    inputs:
      name:
        description: "Provide first name"
        required: true
        type: "string"
      last_name:
        description: "Provide last name"
        required: true
        type: "string"
jobs:
  print_name:
    runs-on: ubuntu-latest
    steps:
      - name: Echo name
        run: echo "Hello ${{ inputs.name }}! 
